# Generated by Django 4.2.26 on 2025-12-24 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("sla_minutes", models.IntegerField(default=60)),
                ("health_target_success_rate", models.FloatField(default=0.95)),
                ("health_window_runs", models.IntegerField(default=20)),
                (
                    "prefect_deployment_name",
                    models.CharField(blank=True, max_length=200),
                ),
                ("owner", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("accent", models.CharField(default="electric", max_length=40)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("allowed_groups", models.ManyToManyField(blank=True, to="auth.group")),
            ],
            options={
                "permissions": [
                    ("can_trigger_pipeline", "Can trigger pipeline runs"),
                    ("can_view_pipeline", "Can view pipeline dashboards"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefect_flow_run_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "prefect_state",
                    models.CharField(db_index=True, default="UNKNOWN", max_length=40),
                ),
                ("triggered_by", models.CharField(blank=True, max_length=120)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("rows_extracted", models.IntegerField(blank=True, null=True)),
                ("rows_loaded", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="pipeline.pipeline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PipelineArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("value", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="pipeline.pipelinerun",
                    ),
                ),
            ],
            options={
                "unique_together": {("run", "key")},
            },
        ),
    ]
