# Generated by Django 4.2.26 on 2025-12-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(max_length=10)),
                ("conference", models.CharField(blank=True, max_length=50)),
                ("division", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("jersey", models.CharField(blank=True, max_length=10)),
                ("position", models.CharField(blank=True, max_length=20)),
                ("height", models.CharField(blank=True, max_length=20)),
                ("weight", models.CharField(blank=True, max_length=20)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("headshot_url", models.URLField(blank=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="analytics.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.IntegerField(unique=True)),
                ("date", models.DateTimeField()),
                ("home_team_score", models.IntegerField(blank=True, null=True)),
                ("visitor_team_score", models.IntegerField(blank=True, null=True)),
                ("season", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "home_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_games",
                        to="analytics.team",
                    ),
                ),
                (
                    "visitor_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_games",
                        to="analytics.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamSeasonStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("ppg", models.FloatField(blank=True, null=True)),
                ("rpg", models.FloatField(blank=True, null=True)),
                ("apg", models.FloatField(blank=True, null=True)),
                ("net_rating", models.FloatField(blank=True, null=True)),
                ("off_rating", models.FloatField(blank=True, null=True)),
                ("def_rating", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="analytics.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "season")},
            },
        ),
        migrations.CreateModel(
            name="SeasonAverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("games_played", models.IntegerField(default=0)),
                ("minutes", models.CharField(blank=True, max_length=10)),
                ("points", models.FloatField(default=0)),
                ("rebounds", models.FloatField(default=0)),
                ("assists", models.FloatField(default=0)),
                ("steals", models.FloatField(default=0)),
                ("blocks", models.FloatField(default=0)),
                ("turnovers", models.FloatField(default=0)),
                ("fg_pct", models.FloatField(blank=True, null=True)),
                ("fg3_pct", models.FloatField(blank=True, null=True)),
                ("ft_pct", models.FloatField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_averages",
                        to="analytics.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "season")},
            },
        ),
        migrations.CreateModel(
            name="PlayerGameStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_date", models.DateField()),
                ("opponent", models.CharField(max_length=64)),
                ("points", models.FloatField()),
                ("rebounds", models.FloatField()),
                ("assists", models.FloatField()),
                ("minutes", models.FloatField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_stats",
                        to="analytics.player",
                    ),
                ),
            ],
            options={
                "ordering": ["game_date"],
                "unique_together": {("player", "game_date")},
            },
        ),
    ]
