# Generated by Django 5.2.8 on 2025-11-29 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='away_team',
            new_name='visitor_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.AddField(
            model_name='game',
            name='period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='visitor_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='external_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='external_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(default='UNK', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='external_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='SeasonAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('minutes', models.CharField(max_length=20)),
                ('points', models.FloatField()),
                ('rebounds', models.FloatField()),
                ('assists', models.FloatField()),
                ('steals', models.FloatField()),
                ('blocks', models.FloatField()),
                ('turnovers', models.FloatField()),
                ('fg_pct', models.FloatField()),
                ('fg3_pct', models.FloatField()),
                ('ft_pct', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.player')),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
        migrations.DeleteModel(
            name='PlayerGameStats',
        ),
    ]
