# Generated by Django 4.2.26 on 2025-12-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_rename_away_team_game_visitor_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="headshot_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="player",
            name="jersey",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="game",
            name="period",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="player",
            name="external_id",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="height",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="analytics.team",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="weight",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="assists",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="blocks",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="fg3_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="fg_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="ft_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="games_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="minutes",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_averages",
                to="analytics.player",
            ),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="points",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="rebounds",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="steals",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="seasonaverage",
            name="turnovers",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="conference",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="team",
            name="division",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="team",
            name="external_id",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="TeamSeasonStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("ppg", models.FloatField(blank=True, null=True)),
                ("rpg", models.FloatField(blank=True, null=True)),
                ("apg", models.FloatField(blank=True, null=True)),
                ("net_rating", models.FloatField(blank=True, null=True)),
                ("off_rating", models.FloatField(blank=True, null=True)),
                ("def_rating", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="analytics.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "season")},
            },
        ),
        migrations.CreateModel(
            name="PlayerGameStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_date", models.DateField()),
                ("opponent", models.CharField(max_length=64)),
                ("points", models.FloatField()),
                ("rebounds", models.FloatField()),
                ("assists", models.FloatField()),
                ("minutes", models.FloatField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_stats",
                        to="analytics.player",
                    ),
                ),
            ],
            options={
                "ordering": ["game_date"],
                "unique_together": {("player", "game_date")},
            },
        ),
    ]
