# Generated by Django 4.2.26 on 2025-12-03 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_player_age_player_headshot_url_player_jersey_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="period",
            new_name="home_team_score",
        ),
        migrations.RemoveField(
            model_name="game",
            name="home_score",
        ),
        migrations.RemoveField(
            model_name="game",
            name="visitor_score",
        ),
        migrations.AddField(
            model_name="game",
            name="visitor_team_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_games",
                to="analytics.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="season",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="visitor_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitor_games",
                to="analytics.team",
            ),
        ),
    ]
