# Generated by Django 4.2.26 on 2025-12-25 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sentinel", "0001_init"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="event",
            new_name="sentinel_ev_industr_099353_idx",
            old_name="sentinel_e_ind_ts",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="sentinel_ev_event_t_580874_idx",
            old_name="sentinel_e_type_ts",
        ),
        migrations.RenameIndex(
            model_name="metric",
            new_name="sentinel_me_industr_50ac48_idx",
            old_name="sentinel_m_ind_kpi_ts",
        ),
    ]
