# Generated by Django 4.2.26 on 2026-01-05 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["state", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReadmissionObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measure_name", models.CharField(db_index=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("excess_readmission_ratio", models.FloatField(blank=True, null=True)),
                ("expected_readmission_rate", models.FloatField(blank=True, null=True)),
                (
                    "predicted_readmission_rate",
                    models.FloatField(blank=True, null=True),
                ),
                ("number_of_discharges", models.IntegerField(blank=True, null=True)),
                ("number_of_readmissions", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="dashboard.facility",
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "facility__state", "facility__name"],
                "indexes": [
                    models.Index(
                        fields=["measure_name"], name="dashboard_r_measure_c06f0e_idx"
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="dashboard_r_start_d_c065ab_idx",
                    ),
                    models.Index(
                        fields=["facility"], name="dashboard_r_facilit_6cebcb_idx"
                    ),
                ],
            },
        ),
    ]
