mse_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: mse
      schema: analytics
      threads: 4
