# Generated by Django 4.2.26 on 2026-01-14 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("risk_spike", "risk_spike"),
                            ("fraud_signal", "fraud_signal"),
                            ("portfolio_alert", "portfolio_alert"),
                            ("system", "system"),
                        ],
                        max_length=32,
                    ),
                ),
                ("severity", models.PositiveSmallIntegerField(default=2)),
                ("title", models.CharField(max_length=120)),
                ("detail", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_id", models.CharField(max_length=32, unique=True)),
                ("origination_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("apr", models.DecimalField(decimal_places=2, max_digits=6)),
                ("term_months", models.PositiveIntegerField(default=36)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        max_length=1,
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("fico_band", models.CharField(default="680-719", max_length=16)),
                (
                    "purpose",
                    models.CharField(default="debt_consolidation", max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "current"),
                            ("late", "late"),
                            ("default", "default"),
                            ("paid", "paid"),
                        ],
                        default="current",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of", models.DateField()),
                (
                    "principal_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "interest_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="dashboards.loan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of", models.DateField(db_index=True)),
                (
                    "portfolio_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "revenue_interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "chargeoffs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "default_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "late_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "expected_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("as_of",)},
            },
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["origination_date"], name="dashboards__origina_b365b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["grade"], name="dashboards__grade_141d58_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["state"], name="dashboards__state_e44823_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["status"], name="dashboards__status_982384_idx"),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["ts", "event_type"], name="dashboards__ts_e83203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["as_of"], name="dashboards__as_of_8ff9bf_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["is_late"], name="dashboards__is_late_7c21aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["is_default"], name="dashboards__is_defa_935596_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("loan", "as_of")},
        ),
    ]
