# Generated by Django 4.2.26 on 2025-12-15 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField(db_index=True, unique=True)),
                ("conference", models.CharField(blank=True, default="", max_length=64)),
                ("city", models.CharField(blank=True, default="", max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=64)),
                ("full_name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "abbreviation",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "primary_hex",
                    models.CharField(blank=True, default="#1f6fff", max_length=16),
                ),
                (
                    "secondary_hex",
                    models.CharField(blank=True, default="#ff2a3a", max_length=16),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField(db_index=True, unique=True)),
                ("first_name", models.CharField(blank=True, default="", max_length=64)),
                ("last_name", models.CharField(blank=True, default="", max_length=64)),
                ("position", models.CharField(blank=True, default="", max_length=32)),
                (
                    "position_abbreviation",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("height", models.CharField(blank=True, default="", max_length=16)),
                ("weight", models.CharField(blank=True, default="", max_length=16)),
                (
                    "jersey_number",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("college", models.CharField(blank=True, default="", max_length=128)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("headshot_url", models.URLField(blank=True, default="")),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="mystics_site.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField(db_index=True, unique=True)),
                ("date_utc", models.DateTimeField(blank=True, null=True)),
                ("season", models.IntegerField(db_index=True)),
                ("postseason", models.BooleanField(default=False)),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                ("period", models.IntegerField(blank=True, null=True)),
                ("time", models.CharField(blank=True, default="", max_length=16)),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_games",
                        to="mystics_site.team",
                    ),
                ),
                (
                    "visitor_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_games",
                        to="mystics_site.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fgm", models.IntegerField(blank=True, null=True)),
                ("fga", models.IntegerField(blank=True, null=True)),
                ("fg_pct", models.FloatField(blank=True, null=True)),
                ("fg3m", models.IntegerField(blank=True, null=True)),
                ("fg3a", models.IntegerField(blank=True, null=True)),
                ("fg3_pct", models.FloatField(blank=True, null=True)),
                ("ftm", models.IntegerField(blank=True, null=True)),
                ("fta", models.IntegerField(blank=True, null=True)),
                ("ft_pct", models.FloatField(blank=True, null=True)),
                ("oreb", models.IntegerField(blank=True, null=True)),
                ("dreb", models.IntegerField(blank=True, null=True)),
                ("reb", models.IntegerField(blank=True, null=True)),
                ("ast", models.IntegerField(blank=True, null=True)),
                ("stl", models.IntegerField(blank=True, null=True)),
                ("blk", models.IntegerField(blank=True, null=True)),
                ("turnovers", models.IntegerField(blank=True, null=True)),
                ("fouls", models.IntegerField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_stats",
                        to="mystics_site.game",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_team_stats",
                        to="mystics_site.team",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["team"], name="mystics_sit_team_id_549581_idx")
                ],
                "unique_together": {("game", "team")},
            },
        ),
        migrations.CreateModel(
            name="PlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min", models.CharField(blank=True, default="", max_length=8)),
                ("fgm", models.IntegerField(blank=True, null=True)),
                ("fga", models.IntegerField(blank=True, null=True)),
                ("fg3m", models.IntegerField(blank=True, null=True)),
                ("fg3a", models.IntegerField(blank=True, null=True)),
                ("ftm", models.IntegerField(blank=True, null=True)),
                ("fta", models.IntegerField(blank=True, null=True)),
                ("oreb", models.IntegerField(blank=True, null=True)),
                ("dreb", models.IntegerField(blank=True, null=True)),
                ("reb", models.IntegerField(blank=True, null=True)),
                ("ast", models.IntegerField(blank=True, null=True)),
                ("stl", models.IntegerField(blank=True, null=True)),
                ("blk", models.IntegerField(blank=True, null=True)),
                ("turnover", models.IntegerField(blank=True, null=True)),
                ("pf", models.IntegerField(blank=True, null=True)),
                ("pts", models.IntegerField(blank=True, null=True)),
                ("plus_minus", models.IntegerField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="mystics_site.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_stats",
                        to="mystics_site.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="mystics_site.team",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["player"], name="mystics_sit_player__33a713_idx"
                    ),
                    models.Index(
                        fields=["team"], name="mystics_sit_team_id_0debea_idx"
                    ),
                ],
                "unique_together": {("game", "player", "team")},
            },
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["season", "postseason"], name="mystics_sit_season_a90845_idx"
            ),
        ),
    ]
