# Generated by Django 4.2.26 on 2025-12-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystics_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-date_utc"]},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["full_name"]},
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="mystics_sit_last_na_9c9ca1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playerstat",
            index=models.Index(fields=["game"], name="mystics_sit_game_id_67e00d_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["conference"], name="mystics_sit_confere_fe1b67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["abbreviation"], name="mystics_sit_abbrevi_b0dceb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamstat",
            index=models.Index(fields=["game"], name="mystics_sit_game_id_36469c_idx"),
        ),
    ]
